# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useroperation', '0003_auto_20171218_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='msg_type',
            new_name='message_type',
        ),
    ]
