# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_auto_20171219_1628'),
        ('trade', '0003_auto_20171218_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('paying', '待支付')], default='paying', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.TextField(verbose_name='订单留言'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
