# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20180105_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '交易超时'), ('TRADE_SUCCESS', '交易成功'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=20, verbose_name='订单状态'),
        ),
    ]
