# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='userwho', max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
